[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true

[project]
name = "customer-support-ai"
version = "1.0.0"
description = "Advanced Customer Support AI System"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "sentence-transformers>=2.2.0",
    "langchain>=0.0.300",
    "langchain-community>=0.0.10",
    "langchain-huggingface>=0.0.5",
    "chromadb>=0.4.0",
    "scikit-learn>=1.0.0",
    "numpy>=1.21.0",
    "python-dotenv>=1.0.0"
]